name: map
description: Map package used to handle process related to Google Map locations.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  authentication:
    path: ../authentication
  firebase_db:
    path: ../firebase_db
  service:
    path: ../service
  better_home: 
    path: ../../  

  cupertino_icons: ^1.0.2
  mvc_pattern: ^8.12.0
  provider: ^6.0.5
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets: