name: better_home
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # personal packages
  authentication:
    path: ./packages/authentication
  firebase_data:
    path: ./packages/firebase_data
  service:
    path: ./packages/service
  map:
    path: ./packages/map
  user_management:
    path: ./packages/user_management

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.3.0
  provider: ^6.0.5
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.7.1
  mvc_pattern: ^8.12.0
  file_picker: ^5.2.5
  google_maps_flutter: ^2.2.5
  flutter_stripe: ^9.1.1
  http:
  firebase_database: ^10.1.1
  firebase_auth_mocks: ^0.11.0
  firebase_messaging: ^14.6.1
  cloud_functions: ^4.3.1
  firebase_analytics: ^10.4.1
  flutter_local_notifications: ^14.1.0
  shared_preferences: ^2.0.18
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/people_img.svg
    - assets/betterhome_logo.png
    - assets/renovation_img.jpg
    - assets/leakage_repair_img.jpeg
    - assets/aircon_img.jpg
    - assets/roof_repair_img.jpg
    - assets/serviceDescription.json
    - assets/serviceVariations.json
    - assets/accept_tasks_img.svg
    - assets/drainage_img.jpg
    - assets/water_heater_repair.jpg
    - assets/toilet_repair.jpg
    - assets/roof_replace.jpg
    - assets/light_install.jpg
    - assets/extend_wiring.jpg
    - assets/safety_inspection.jpg
    - assets/window_repair.jpg
    - assets/door_repair.jpg
    - assets/internal_painting.png
    - assets/external_painting.jpg
    - assets/wallpaper.jpg
