name: better_home
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # personal packages
  authentication:
    path: ./packages/authentication
  firebase_db:
    path: ./packages/firebase_db
  service:
    path: ./packages/service

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.3.0
  provider: ^6.0.5
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/people_img.svg
    - assets/betterhome_logo.png
