name: better_home
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # personal packages
  authentication:
    path: ./packages/authentication
  firebase_data:
    path: ./packages/firebase_data
  service:
    path: ./packages/service
  map:
    path: ./packages/map
  user_management:
    path: ./packages/user_management

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.3.0
  provider: ^6.0.5
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.4
  mvc_pattern: ^8.12.0
  file_picker: ^5.2.5
  google_maps_flutter: ^2.2.5
  flutter_stripe: ^9.1.1
  http:
  firebase_database: ^10.1.1
  firebase_auth_mocks: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/people_img.svg
    - assets/betterhome_logo.png
    - assets/renovation_img.jpg
    - assets/leakage_repair_img.jpeg
    - assets/aircon_img.jpg
    - assets/roof_repair_img.jpg
    - assets/serviceDescription.json
    - assets/serviceVariations.json
    - assets/accept_tasks_img.svg
