name: better_home
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # personal packages
  authentication:
    path: ./packages/authentication

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  #mvc_pattern: ^8.12.0
  firebase_auth: ^4.2.9
  provider: ^6.0.5
  #file_picker: ^5.2.5
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.4
  #pinput: ^2.2.31
  #shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/people_img.svg
    - assets/betterhome_logo.png
