name: service
description: Service package used to handle functionalities related to customer and technician's services.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  better_home: 
    path: ../../
  map:
    path: ../map
  firebase_data:
    path: ../firebase_data
  authentication:
    path: ../authentication
  user_management:
    path: ../user_management
    
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  mvc_pattern: ^8.12.0
  provider: ^6.0.5
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.7.1
  google_maps_flutter: ^2.2.5
  shared_preferences: ^2.0.18
  intl: ^0.17.0
  image_picker: ^0.8.7+4
  timezone: ^0.9.2
  flutter_stripe: ^9.1.1
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  table_calendar: ^3.0.8
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets: