name: firebase_data
description: Firebase Database package used for managing user data and notification.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  better_home: 
    path: ../../
  authentication:
    path: ../authentication
  user_management:
    path: ../user_management
    
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  mvc_pattern: ^8.12.0
  file_picker: ^5.2.5
  image_picker: ^0.8.7+4
  firebase_storage: ^11.0.14
  provider: ^6.0.5
  cloud_firestore: ^4.4.4
  path: 1.8.3
  shared_preferences: ^2.0.18
  photo_view: ^0.14.0
  firebase_database: ^10.1.1
  firebase_messaging: ^14.6.0
  http:
  cloud_functions: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets: